version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements_docs.txt
    - method: pip
      path: .
      extra_requirements:
        - all

submodules:
  include: all